import { ApiClientError, apiClient } from './apiClient';

export type ObjectionStatus = 'OPEN' | 'RESOLVED' | 'DISMISSED';
export type Objection = { id:string; applicantId:string; projectDecisionId:string; projectDecisionVersion:number; reason:string; creator:{id:string;name:string}; status:ObjectionStatus; resolutionNote:string|null; reviewedByUserId:string|null; version:number; createdAt:number; updatedAt:number };
export type ObjectionsResponse = { items:readonly Objection[]; pagination:{page:number;pageSize:number;total:number;totalPages:number} };
export type ObjectionsQuery = { status:ObjectionStatus|null; page:number; pageSize:number };

function isRecord(value:unknown):value is Record<string,unknown>{return typeof value==='object'&&value!==null;}
function finite(value:unknown):value is number{return typeof value==='number'&&Number.isFinite(value);}
function positive(value:unknown):value is number{return finite(value)&&Number.isInteger(value)&&value>0;}
function status(value:unknown):value is ObjectionStatus{return value==='OPEN'||value==='RESOLVED'||value==='DISMISSED';}
function nullableString(value:unknown):value is string|null{return typeof value==='string'||value===null;}
function parseItem(value:unknown):Objection|null{if(!isRecord(value)||typeof value.id!=='string'||typeof value.applicantId!=='string'||typeof value.projectDecisionId!=='string'||!positive(value.projectDecisionVersion)||typeof value.reason!=='string'||!isRecord(value.creator)||typeof value.creator.id!=='string'||typeof value.creator.name!=='string'||!status(value.status)||!nullableString(value.resolutionNote)||!nullableString(value.reviewedByUserId)||!positive(value.version)||!finite(value.createdAt)||!finite(value.updatedAt))return null;return{id:value.id,applicantId:value.applicantId,projectDecisionId:value.projectDecisionId,projectDecisionVersion:value.projectDecisionVersion,reason:value.reason,creator:{id:value.creator.id,name:value.creator.name},status:value.status,resolutionNote:value.resolutionNote,reviewedByUserId:value.reviewedByUserId,version:value.version,createdAt:value.createdAt,updatedAt:value.updatedAt};}
function parse(value:unknown):ObjectionsResponse|null{if(!isRecord(value)||!Array.isArray(value.items)||!isRecord(value.pagination)||!positive(value.pagination.page)||!positive(value.pagination.pageSize)||!finite(value.pagination.total)||!finite(value.pagination.totalPages))return null;const items:Objection[]=[];for(const valueItem of value.items){const item=parseItem(valueItem);if(!item)return null;items.push(item);}return{items,pagination:{page:value.pagination.page,pageSize:value.pagination.pageSize,total:value.pagination.total,totalPages:value.pagination.totalPages}};}
function path(query:ObjectionsQuery):string{const params=new URLSearchParams({page:String(query.page),pageSize:String(query.pageSize)});if(query.status)params.set('status',query.status);return`/objections?${params.toString()}`;}
export async function getObjections(query:ObjectionsQuery,signal:AbortSignal):Promise<ObjectionsResponse>{const payload=await apiClient.requestJson(path(query),{signal,authentication:'required'});const response=parse(payload);if(!response)throw new ApiClientError({kind:'invalid-response'});return response;}
export async function createObjection(decisionId:string,reason:string,expectedDecisionVersion:number):Promise<void>{await apiClient.requestJson(`/project-decisions/${encodeURIComponent(decisionId)}/objections`,{method:'POST',jsonBody:{reason,expectedDecisionVersion},authentication:'required'});}
export async function reviewObjection(objectionId:string,statusValue:'RESOLVED'|'DISMISSED',resolutionNote:string,expectedVersion:number):Promise<void>{await apiClient.requestJson(`/objections/${encodeURIComponent(objectionId)}/review`,{method:'PUT',jsonBody:{status:statusValue,resolutionNote,expectedVersion},authentication:'required'});}
