import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Archive, Check, ChevronLeft, ChevronRight, Plus } from 'lucide-react';
import { useSearchParams } from 'react-router-dom';
import { archiveMessage, getInbox, getMessageRecipients, markMessageRead, sendMessage, type InboxFolder, type InboxMessage, type InboxResponse, type InboxUser } from '../api/inboxApi';
import { ApiClientError } from '../api/apiClient';
import '../styles/communication.css';

const pageSize = 25;
function isFolder(value: string | null): value is InboxFolder { return value === 'inbox' || value === 'sent'; }
function safePage(value: string | null): number { const number = Number(value); return Number.isSafeInteger(number) && number > 0 ? number : 1; }
function date(value: number): string { const item = new Date(value * 1000); return Number.isFinite(item.getTime()) ? new Intl.DateTimeFormat('ar-SA-u-ca-gregory', { dateStyle: 'medium', timeStyle: 'short' }).format(item) : 'غير متوفر'; }
function errorText(error: ApiClientError): string { if (error.status === 403) return 'لا تملك صلاحية تنفيذ هذه العملية.'; if (error.status === 404) return 'هذه الرسالة لم تعد متاحة.'; if (error.kind === 'network') return 'تعذر الاتصال بالنظام. تحقق من الشبكة ثم حاول مرة أخرى.'; return 'تعذر إكمال العملية. حاول مرة أخرى.'; }

export function InboxWorkspace() {
  const [params, setParams] = useSearchParams();
  const folderParam = params.get('folder');
  const folder: InboxFolder = isFolder(folderParam) ? folderParam : 'inbox';
  const page = safePage(params.get('page'));
  const [data, setData] = useState<InboxResponse | null>(null); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState<ApiClientError | null>(null); const [reload, setReload] = useState(0);
  const [isComposeOpen, setComposeOpen] = useState(false); const [recipients, setRecipients] = useState<readonly InboxUser[] | null>(null); const [recipientsError, setRecipientsError] = useState<string | null>(null); const [recipientId, setRecipientId] = useState(''); const [content, setContent] = useState(''); const [isSending, setIsSending] = useState(false); const [mutationError, setMutationError] = useState<string | null>(null); const [actionId, setActionId] = useState<string | null>(null);
  const refresh = useCallback(() => setReload((value) => value + 1), []);
  const updateUrl = (nextFolder: InboxFolder, nextPage: number) => { const next = new URLSearchParams(); next.set('folder', nextFolder); if (nextPage > 1) next.set('page', String(nextPage)); setParams(next); };
  useEffect(() => { const controller = new AbortController(); let current = true; const load = async () => { setIsLoading(true); setError(null); try { const response = await getInbox(folder, page, pageSize, controller.signal); if (current) setData(response); } catch (requestError) { if (!current || controller.signal.aborted) return; setData(null); setError(requestError instanceof ApiClientError ? requestError : new ApiClientError({ kind: 'invalid-response' })); } finally { if (current) setIsLoading(false); } }; void load(); return () => { current = false; controller.abort(); }; }, [folder, page, reload]);
  useEffect(() => { if (!isComposeOpen) return undefined; const controller = new AbortController(); let current = true; const load = async () => { setRecipients(null); setRecipientsError(null); try { const users = await getMessageRecipients(controller.signal); if (current) { setRecipients(users); setRecipientId(users[0]?.id ?? ''); } } catch (requestError) { if (!current || controller.signal.aborted) return; setRecipientsError(errorText(requestError instanceof ApiClientError ? requestError : new ApiClientError({ kind: 'invalid-response' }))); } }; void load(); return () => { current = false; controller.abort(); }; }, [isComposeOpen]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const trimmed = content.trim(); if (isSending) return; if (!recipientId) { setMutationError('اختر مستلمًا قبل الإرسال.'); return; } if (!trimmed) { setMutationError('اكتب رسالة قبل الإرسال.'); return; } if (trimmed.length > 2000) { setMutationError('يجب ألا تتجاوز الرسالة 2000 حرف.'); return; } setMutationError(null); setIsSending(true); try { await sendMessage(recipientId, trimmed); setComposeOpen(false); setContent(''); if (folder === 'sent') refresh(); } catch (requestError) { setMutationError(errorText(requestError instanceof ApiClientError ? requestError : new ApiClientError({ kind: 'invalid-response' }))); } finally { setIsSending(false); } };
  const runAction = async (message: InboxMessage, action: 'read' | 'archive') => { if (actionId) return; setMutationError(null); setActionId(message.id); try { if (action === 'read') await markMessageRead(message.id); else await archiveMessage(message.id); refresh(); } catch (requestError) { setMutationError(errorText(requestError instanceof ApiClientError ? requestError : new ApiClientError({ kind: 'invalid-response' }))); } finally { setActionId(null); } };
  return <section className="inbox-page" aria-labelledby="inbox-title"><header className="inbox-page__header"><div><p>التواصل الداخلي</p><h1 id="inbox-title">الوارد</h1></div><button type="button" onClick={() => { setMutationError(null); setComposeOpen(true); }}><Plus aria-hidden="true" size={18} />رسالة جديدة</button></header>
    <div className="inbox-tabs" role="tablist" aria-label="مجلد الرسائل"><button role="tab" aria-selected={folder === 'inbox'} type="button" onClick={() => updateUrl('inbox', 1)}>الوارد</button><button role="tab" aria-selected={folder === 'sent'} type="button" onClick={() => updateUrl('sent', 1)}>المرسل</button></div>
    {mutationError ? <p className="communication-error" role="alert">{mutationError}</p> : null}
    {isComposeOpen ? <form className="communication-composer inbox-compose" onSubmit={submit}><h2>رسالة جديدة</h2>{recipients === null && !recipientsError ? <p role="status">جارٍ تحميل المستلمين.</p> : null}{recipientsError ? <p className="communication-error" role="alert">{recipientsError}</p> : null}{recipients?.length === 0 ? <p className="communication-state">لا يوجد مستلمون متاحون حاليًا.</p> : null}{recipients && recipients.length > 0 ? <><label htmlFor="message-recipient">المستلم</label><select id="message-recipient" value={recipientId} disabled={isSending} onChange={(event) => setRecipientId(event.target.value)}>{recipients.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select><label htmlFor="message-content">الرسالة</label><textarea id="message-content" value={content} disabled={isSending} onChange={(event) => setContent(event.target.value)} /><button type="submit" disabled={isSending}>{isSending ? 'جارٍ الإرسال…' : 'إرسال الرسالة'}</button></> : null}<button type="button" disabled={isSending} onClick={() => setComposeOpen(false)}>إلغاء</button></form> : null}
    {isLoading ? <p className="communication-state" role="status">جارٍ تحميل الرسائل.</p> : null}{!isLoading && error ? <div className="communication-state" role="alert"><p>تعذر تحميل الرسائل.</p><button type="button" onClick={refresh}>إعادة المحاولة</button></div> : null}{!isLoading && !error && data?.items.length === 0 ? <p className="communication-state">{folder === 'inbox' ? 'لا توجد رسائل في الوارد' : 'لم ترسل رسائل حتى الآن'}</p> : null}
    {!isLoading && !error && data && data.items.length > 0 ? <div className="inbox-list">{data.items.map((message) => <article key={message.id} className={`inbox-message${folder === 'inbox' && message.readAt === null ? ' inbox-message--unread' : ''}`}><header><div><strong>{folder === 'inbox' ? message.sender.name : message.recipient.name}</strong><span>{folder === 'inbox' ? 'المرسل' : 'المستلم'} · {date(message.createdAt)}</span></div>{folder === 'inbox' && message.readAt === null ? <span>غير مقروءة</span> : null}</header><p>{message.content}</p>{folder === 'inbox' ? <div><button type="button" disabled={actionId !== null} onClick={() => void runAction(message, 'read')}><Check aria-hidden="true" size={16} />تعليم كمقروءة</button><button type="button" disabled={actionId !== null} onClick={() => void runAction(message, 'archive')}><Archive aria-hidden="true" size={16} />أرشفة</button></div> : null}</article>)}</div> : null}
    {data && data.pagination.totalPages > 1 ? <nav className="communication-pagination" aria-label="صفحات الرسائل"><button type="button" disabled={data.pagination.page <= 1} onClick={() => updateUrl(folder, data.pagination.page - 1)}><ChevronRight aria-hidden="true" size={18} />السابق</button><p>الصفحة {data.pagination.page} من {data.pagination.totalPages}</p><button type="button" disabled={data.pagination.page >= data.pagination.totalPages} onClick={() => updateUrl(folder, data.pagination.page + 1)}>التالي<ChevronLeft aria-hidden="true" size={18} /></button></nav> : null}
  </section>;
}
